[settings]
python.uv_venv_auto = true

[tools]
node = "latest" # for pyright
uv = "latest"

[tasks."py:check:lint"]
run = [
    "uv run ruff format --check .",
    "uv run ruff check .",
]

[tasks."py:check:types"]
# keep an eye on https://github.com/astral-sh/ty
# Note: https://sinon.github.io/future-python-type-checkers/
# Note: https://htmlpreview.github.io/?https://github.com/python/typing/blob/main/conformance/results/results.html
run = "pyright"

[tasks."py:run"]
run = "uv run cmd/main.py"

[tasks."py:build"]
run = "uv build"
